spring.application.name=boost

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/study_db
spring.datasource.username=root
spring.datasource.password=

spring.data.redis.host=redis-11678.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
spring.data.redis.username=default
spring.data.redis.password=czQWm99WQZ8KdMDI1sB3cxRmrCLNamUm
spring.data.redis.port=11678

management.endpoints.web.base-path=/api/actuator
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled= true
management.health.retry.enabled= true

# Redis ?? ??? ?????? ??
# Actuator? ??
resilience4j.circuitbreaker.instances.redisCB.registerHealthIndicator=true
# ?? 10? ??
resilience4j.circuitbreaker.instances.redisCB.slidingWindowSize=10
# ??? 50% ???? open
resilience4j.circuitbreaker.instances.redisCB.failureRateThreshold=50
# open ?? ?? ??
resilience4j.circuitbreaker.instances.redisCB.waitDurationInOpenState=30s
# half-open ? ?? ?? ?
resilience4j.circuitbreaker.instances.redisCB.permittedNumberOfCallsInHalfOpenState=3

